project:
  type: website

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

website:
  open-graph: true
  navbar:
    background: primary
    search: true

metadata-files: [nbdev.yml, sidebar.yml]
